version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sight-words-tool"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rttsapwm17oy"
s3_prefix = "sight-words-tool"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

